/** Auto-generated by scripts/narrative-generate-assets.mjs — do not hand-edit */
import { NARRATIVE_PUBLIC_BASE } from "../config";

function p(rel: string) {
  return `${NARRATIVE_PUBLIC_BASE}/${rel}`;
}

const manifestData = {
  version: 1,
  symbolFiles: {
    A1: p("assets/symbols/a1-feather-crown.svg"),
    A2: p("assets/symbols/a2-profile-headwear.svg"),
    A3: p("assets/symbols/a3-round-earrings.svg"),
    A4: p("assets/symbols/a4-garment-edge.svg"),
    A5: p("assets/symbols/a5-collar.svg"),
    A6: p("assets/symbols/a6-curved-sash.svg"),
    A7: p("assets/symbols/a7-waist-ornament.svg"),
    A8: p("assets/symbols/a8-crown-ornament.svg"),
    B1: p("assets/symbols/b1-mortar.svg"),
    B2: p("assets/symbols/b2-umbrella.svg"),
    B3: p("assets/symbols/b3-flute.svg"),
    B4: p("assets/symbols/b4-flower-vine.svg"),
    B5: p("assets/symbols/b5-cat.svg"),
    B6: p("assets/symbols/b6-bird.svg"),
    B7: p("assets/symbols/b7-clay-pot.svg"),
    B8: p("assets/symbols/b8-seated-animal.svg"),
    B9: p("assets/symbols/b9-standing-dog.svg"),
    C1: p("assets/symbols/c1-open-palm.svg"),
    C2: p("assets/symbols/c2-ox-horn.svg"),
    C3: p("assets/symbols/c3-sun-spiral.svg"),
    C4: p("assets/symbols/c4-elephant-totem.svg"),
    C5: p("assets/symbols/c5-flower-ritual.svg"),
    C6: p("assets/symbols/c6-double-dance.svg"),
    C7: p("assets/symbols/c7-horned-skull.svg"),
    C8: p("assets/symbols/c8-peacock.svg"),
  },
  uiFiles: {
    "ancient-road": p("assets/ui/ancient-road.svg"),
    "bai-village": p("assets/ui/bai-village.svg"),
    "benzhu-gate": p("assets/ui/benzhu-gate.svg"),
    "button-bg": p("assets/ui/button-bg.svg"),
    "chapter-badge": p("assets/ui/chapter-badge.svg"),
    "chapter-rail-bg": p("assets/ui/chapter-rail-bg.svg"),
    "cloth-overlay": p("assets/ui/cloth-overlay.svg"),
    "erhai-waterline": p("assets/ui/erhai-waterline.svg"),
    "flower-vine-accent": p("assets/ui/flower-vine-accent.svg"),
    "hotspot-ring": p("assets/ui/hotspot-ring.svg"),
    "houses-compare": p("assets/ui/houses-compare.svg"),
    "panel-bg": p("assets/ui/panel-bg.svg"),
    "popover-frame": p("assets/ui/popover-frame.svg"),
    "progress-marker": p("assets/ui/progress-marker.svg"),
    "rice-paper-texture": p("assets/ui/rice-paper-texture.svg"),
    "screen-wall-frame": p("assets/ui/screen-wall-frame.svg"),
    "selected-highlight": p("assets/ui/selected-highlight.svg"),
    "stone-texture": p("assets/ui/stone-texture.svg"),
    "tab-bg": p("assets/ui/tab-bg.svg"),
    "three-tea-cups": p("assets/ui/three-tea-cups.svg"),
  },
} as const;

export type UiFileKey = keyof typeof manifestData.uiFiles;

export default manifestData;
